[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
googleGmsGoogleServices = "4.4.2"
firebaseFirestore = "25.1.3"
firebaseAuth = "23.2.0"
roundedImageView = "2.3.0"
glide = "4.16.0"
glideCompiler = "4.16.0"
pdfboxAndroid = "2.0.27.0"
firebaseui = "8.0.2"
libausbc = "3.3.3"
cardview = "1.0.0"
firebaseStorage = "21.0.1"
core = "1.16.0"
flexbox = "3.0.0"


[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
rounded-image-view = { group = "com.makeramen", name = "roundedimageview", version.ref = "roundedImageView" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glideCompiler" }
pdfbox-android = { group = "com.tom-roush", name = "pdfbox-android", version.ref = "pdfboxAndroid" }
libausbc = { group = "com.github.jiangdongguo.AndroidUSBCamera", name = "libausbc", version.ref = "libausbc"}
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview"}
core = {group = "androidx.core", name = "core", version.ref = "core"}
flexbox = {group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox"}



firebaseui = { group = "com.firebaseui", name = "firebase-ui-firestore", version.ref = "firebaseui" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

